defaults:
  - _self_
  - experiment: null
  - hydra: default

wandb_account: null
save_dir: "logs/"
seed: 27

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  entity: ${wandb_account}
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  project: "Explicit-Implicit"
  save_dir: ${save_dir}
  offline: False
  tags: null