defaults:
  - _self_
  - experiment: null
  - hydra: default

wandb_account: null
save_dir: "logs/"
seed: 27
save: False

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  entity: null
  name: ${experiment.name}
  project: "Explicit-Implicit_${experiment.task_name}"
  save_dir: ${save_dir}
  offline: False
  tags: null
