defaults:
  - _self_
  - experiment: null
  - hydra: default

wandb_account: null
save_dir: "logs/"
seed: 27
save: False

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  entity: ${wandb_account}
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  checkpoint_name: ${logger.name}
  project: "Explicit-Implicit"
  save_dir: ${save_dir}
  offline: False
  tags: ["${experiment.name}"]