defaults:
  - submitit_slurm

account: "rrg-bengioy-ad"
partition: default
cpus_per_task: 6
gres: gpu:1
tasks_per_node: 1
mem_gb: 64
timeout_min: 1440  # 1 day
array_parallelism: 20

setup:
  - "module load python"
  - "source /home/elmo/envs/explicit/bin/activate"